# fly.toml app configuration file generated for extrc on 2024-08-14T01:33:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "klm-algorithms"
primary_region = "jnb"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = [ "app" ]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory = "1gb"

[build.args]
  depot = "false"

[deploy]
  strategy = "immediate"

[env]
  LOG_LEVEL = "debug"
